package com.archivos.fitmanager.ui.inventario;

import com.archivos.fitmanager.controller.EquipoController;
import com.archivos.fitmanager.dao.SucursalDAO;
import com.archivos.fitmanager.db.DBConfig;
import com.archivos.fitmanager.model.Equipo;
import com.archivos.fitmanager.model.Sucursal;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vicente
 */
public class EquipoNuevo extends javax.swing.JPanel {

    private EquipoController equipoController;
    private Connection conn;
    private List<Sucursal> listaSucursales;

    /**
     * Creates new form EquipoNuevo
     */
    public EquipoNuevo() {
        initComponents();
        initControllers();
        cargarEstados();
        cargarSucursales();
        cargarTabla();
        
    }
    
    private void initControllers() {
        try {
            conn = DBConfig.getConnection();
            equipoController = new EquipoController(conn);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al conectar a la base de datos: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
private void cargarEstados() {
        jComboBoxEstado.removeAllItems();
        jComboBoxEstado.addItem("Disponible");
        jComboBoxEstado.addItem("Mantenimiento");
        jComboBoxEstado.addItem("Fuera de servicio");
        jComboBoxEstado.addItem("Reservado");
    }

    private void cargarSucursales() {
        jComboBoxSucursal.removeAllItems();
        SucursalDAO sucursalDAO = new SucursalDAO();
        listaSucursales = sucursalDAO.obtenerTodas();
        for (Sucursal s : listaSucursales) {
            jComboBoxSucursal.addItem(s.getNombre());
        }
    }

    private void cargarTabla() {
        try {
            List<Equipo> equipos = equipoController.obtenerEquipos();
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new String[]{"ID", "Nombre", "Estado", "Sucursal"});
            for (Equipo e : equipos) {
                String sucursalNombre = (e.getIdSucursal() != null) ? 
                        new SucursalDAO().obtenerSucursalPorId(e.getIdSucursal()).getNombre() : "";
                model.addRow(new Object[]{e.getIdEquipo(), e.getNombre(), e.getEstado(), sucursalNombre});
            }
            jTableListaEquipos.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar equipos: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEstado = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        txtNombreEquipo = new javax.swing.JTextField();
        jLabelNombreEquipo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabelTravel2 = new javax.swing.JLabel();
        jLabelSucursal = new javax.swing.JLabel();
        jComboBoxSucursal = new javax.swing.JComboBox<>();
        jPanelContendor = new javax.swing.JPanel();
        jScrollPaneContendor = new javax.swing.JScrollPane();
        jTableListaEquipos = new javax.swing.JTable();
        btnRegistrarEquipo = new javax.swing.JButton();

        setBackground(new java.awt.Color(33, 45, 62));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEstado.setFont(new java.awt.Font("Gotham Thin", 0, 24)); // NOI18N
        jLabelEstado.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEstado.setText("Estado");
        add(jLabelEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 80, 30));

        jComboBoxEstado.setBackground(new java.awt.Color(33, 45, 62));
        jComboBoxEstado.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jComboBoxEstado.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstadoActionPerformed(evt);
            }
        });
        add(jComboBoxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 300, 40));

        txtNombreEquipo.setBackground(new java.awt.Color(33, 45, 62));
        txtNombreEquipo.setFont(new java.awt.Font("Gotham Thin", 0, 24)); // NOI18N
        txtNombreEquipo.setForeground(new java.awt.Color(195, 218, 227));
        txtNombreEquipo.setBorder(null);
        txtNombreEquipo.setCaretColor(new java.awt.Color(73, 181, 172));
        txtNombreEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEquipoActionPerformed(evt);
            }
        });
        txtNombreEquipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreEquipoKeyReleased(evt);
            }
        });
        add(txtNombreEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 300, 50));

        jLabelNombreEquipo.setFont(new java.awt.Font("Gotham Thin", 0, 24)); // NOI18N
        jLabelNombreEquipo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreEquipo.setText("Nombre Equipo");
        add(jLabelNombreEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 180, 30));

        jSeparator3.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator3.setForeground(new java.awt.Color(73, 181, 172));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 310, 10));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("____________");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, -1, 30));

        jLabelTravel2.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 24)); // NOI18N
        jLabelTravel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTravel2.setText("EQUIPO NUEVO");
        add(jLabelTravel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 200, 60));

        jLabelSucursal.setFont(new java.awt.Font("Gotham Thin", 0, 24)); // NOI18N
        jLabelSucursal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSucursal.setText("Sucursal");
        add(jLabelSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 100, 30));

        jComboBoxSucursal.setBackground(new java.awt.Color(33, 45, 62));
        jComboBoxSucursal.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jComboBoxSucursal.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSucursalActionPerformed(evt);
            }
        });
        add(jComboBoxSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 300, 40));

        jPanelContendor.setBackground(new java.awt.Color(33, 45, 62));

        jScrollPaneContendor.setBackground(new java.awt.Color(33, 45, 62));

        jTableListaEquipos.setBackground(new java.awt.Color(33, 45, 62));
        jTableListaEquipos.setForeground(new java.awt.Color(255, 255, 255));
        jTableListaEquipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneContendor.setViewportView(jTableListaEquipos);

        javax.swing.GroupLayout jPanelContendorLayout = new javax.swing.GroupLayout(jPanelContendor);
        jPanelContendor.setLayout(jPanelContendorLayout);
        jPanelContendorLayout.setHorizontalGroup(
            jPanelContendorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContendorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneContendor, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelContendorLayout.setVerticalGroup(
            jPanelContendorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContendorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneContendor, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanelContendor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 490, 320));

        btnRegistrarEquipo.setBackground(new java.awt.Color(73, 181, 172));
        btnRegistrarEquipo.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnRegistrarEquipo.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarEquipo.setText("REGISTRAR");
        btnRegistrarEquipo.setBorderPainted(false);
        btnRegistrarEquipo.setContentAreaFilled(false);
        btnRegistrarEquipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarEquipo.setFocusPainted(false);
        btnRegistrarEquipo.setFocusable(false);
        btnRegistrarEquipo.setRequestFocusEnabled(false);
        btnRegistrarEquipo.setVerifyInputWhenFocusTarget(false);
        btnRegistrarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEquipoActionPerformed(evt);
            }
        });
        add(btnRegistrarEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, 150, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstadoActionPerformed

    }//GEN-LAST:event_jComboBoxEstadoActionPerformed

    private void txtNombreEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEquipoActionPerformed

    private void txtNombreEquipoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreEquipoKeyReleased

    }//GEN-LAST:event_txtNombreEquipoKeyReleased

    private void jComboBoxSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSucursalActionPerformed

    private void btnRegistrarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEquipoActionPerformed
        String nombre = txtNombreEquipo.getText().trim(); // quitamos espacios en blanco
        String estado = (String) jComboBoxEstado.getSelectedItem();

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes ingresar el nombre del equipo",
                    "Validación", JOptionPane.WARNING_MESSAGE);
            txtNombreEquipo.requestFocus();
            return;
        }

        int index = jComboBoxSucursal.getSelectedIndex();
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar una sucursal",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Sucursal seleccionada = listaSucursales.get(index);

        try {
            equipoController.crearEquipo(nombre, estado, seleccionada.getIdSucursal());
            JOptionPane.showMessageDialog(this, "Equipo registrado correctamente",
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);

            txtNombreEquipo.setText("");
            jComboBoxEstado.setSelectedIndex(0);
            jComboBoxSucursal.setSelectedIndex(0);

            cargarTabla();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al registrar equipo: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarEquipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarEquipo;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JComboBox<String> jComboBoxSucursal;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelNombreEquipo;
    private javax.swing.JLabel jLabelSucursal;
    private javax.swing.JLabel jLabelTravel2;
    private javax.swing.JPanel jPanelContendor;
    private javax.swing.JScrollPane jScrollPaneContendor;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTableListaEquipos;
    private javax.swing.JTextField txtNombreEquipo;
    // End of variables declaration//GEN-END:variables
}
