package com.archivos.fitmanager.ui.recepcion;

import com.archivos.fitmanager.controller.AsistenciaController;
import com.archivos.fitmanager.controller.ClienteController;
import com.archivos.fitmanager.db.DBConfig;
import com.archivos.fitmanager.model.Cliente;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;


/**
 *
 * @author vicente
 */
public class Asistencias extends javax.swing.JPanel {
    
    private ClienteController clienteController;
    private AsistenciaController asistenciaController;

    /**
     * Creates new form Asistencias
     */
    public Asistencias(){
        initComponents();
        try {
            Connection conn = DBConfig.getConnection(); 
            this.clienteController = new ClienteController(conn); 
            this.asistenciaController = new AsistenciaController();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        jComboBoxClientesId.setVisible(false);
        jLabelCoincidencias.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSeparador = new javax.swing.JLabel();
        jLabelDescripcion = new javax.swing.JLabel();
        txtNombreUser = new javax.swing.JTextField();
        jLabelNombreCliente = new javax.swing.JLabel();
        txtIdUser = new javax.swing.JTextField();
        jLabelidCliente = new javax.swing.JLabel();
        btnRegistrarAsistencia = new javax.swing.JButton();
        jComboBoxClientesId = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtIdSucursal = new javax.swing.JTextField();
        jLabelidSucursal = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabelCoincidencias = new javax.swing.JLabel();

        setBackground(new java.awt.Color(33, 45, 62));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSeparador.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabelSeparador.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSeparador.setText("____________");
        add(jLabelSeparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, -1, 30));

        jLabelDescripcion.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 24)); // NOI18N
        jLabelDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescripcion.setText("ASISTENCIA");
        add(jLabelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 150, 60));

        txtNombreUser.setBackground(new java.awt.Color(33, 45, 62));
        txtNombreUser.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtNombreUser.setForeground(new java.awt.Color(195, 218, 227));
        txtNombreUser.setBorder(null);
        txtNombreUser.setCaretColor(new java.awt.Color(73, 181, 172));
        txtNombreUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreUserKeyReleased(evt);
            }
        });
        add(txtNombreUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 300, 50));

        jLabelNombreCliente.setFont(new java.awt.Font("Gotham Thin", 0, 24)); // NOI18N
        jLabelNombreCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreCliente.setText("Nombre");
        add(jLabelNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 90, 30));

        txtIdUser.setBackground(new java.awt.Color(33, 45, 62));
        txtIdUser.setFont(new java.awt.Font("Gotham Thin", 0, 24)); // NOI18N
        txtIdUser.setForeground(new java.awt.Color(195, 218, 227));
        txtIdUser.setBorder(null);
        txtIdUser.setCaretColor(new java.awt.Color(73, 181, 172));
        add(txtIdUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 120, 40));

        jLabelidCliente.setFont(new java.awt.Font("Gotham Thin", 0, 24)); // NOI18N
        jLabelidCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelidCliente.setText("ID");
        add(jLabelidCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 40, 30));

        btnRegistrarAsistencia.setBackground(new java.awt.Color(73, 181, 172));
        btnRegistrarAsistencia.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnRegistrarAsistencia.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarAsistencia.setText("REGISTRAR");
        btnRegistrarAsistencia.setBorderPainted(false);
        btnRegistrarAsistencia.setContentAreaFilled(false);
        btnRegistrarAsistencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarAsistencia.setFocusPainted(false);
        btnRegistrarAsistencia.setFocusable(false);
        btnRegistrarAsistencia.setRequestFocusEnabled(false);
        btnRegistrarAsistencia.setVerifyInputWhenFocusTarget(false);
        btnRegistrarAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAsistenciaActionPerformed(evt);
            }
        });
        add(btnRegistrarAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 210, 60));

        jComboBoxClientesId.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jComboBoxClientesId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxClientesId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClientesIdActionPerformed(evt);
            }
        });
        add(jComboBoxClientesId, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 290, -1));

        jSeparator2.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator2.setForeground(new java.awt.Color(73, 181, 172));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 130, 20));

        jSeparator3.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator3.setForeground(new java.awt.Color(73, 181, 172));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 310, 10));

        txtIdSucursal.setBackground(new java.awt.Color(33, 45, 62));
        txtIdSucursal.setFont(new java.awt.Font("Gotham Thin", 0, 24)); // NOI18N
        txtIdSucursal.setForeground(new java.awt.Color(195, 218, 227));
        txtIdSucursal.setBorder(null);
        txtIdSucursal.setCaretColor(new java.awt.Color(73, 181, 172));
        txtIdSucursal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdSucursalKeyReleased(evt);
            }
        });
        add(txtIdSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 110, 50));

        jLabelidSucursal.setFont(new java.awt.Font("Gotham Thin", 0, 24)); // NOI18N
        jLabelidSucursal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelidSucursal.setText("Id Sucursal");
        add(jLabelidSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 120, 30));

        jSeparator4.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator4.setForeground(new java.awt.Color(73, 181, 172));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 140, 10));

        jLabelCoincidencias.setFont(new java.awt.Font("Gotham Thin", 0, 24)); // NOI18N
        jLabelCoincidencias.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCoincidencias.setText("Coincidencias");
        add(jLabelCoincidencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, 160, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAsistenciaActionPerformed
        try {
            String seleccionado = (String) jComboBoxClientesId.getSelectedItem();
            if (seleccionado == null || seleccionado.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente.");
                return;
            }
            int idCliente = Integer.parseInt(seleccionado.split(" - ")[0]);

            if (txtIdSucursal.getText().trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar el ID de la sucursal.");
                return;
            }
            int idSucursal = Integer.parseInt(txtIdSucursal.getText().trim());

            asistenciaController.registrarAsistencia(idCliente, idSucursal);

            javax.swing.JOptionPane.showMessageDialog(this, "Asistencia registrada correctamente.");
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Error registrando asistencia:\n" + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "El ID ingresado no es válido.");
        }
    }//GEN-LAST:event_btnRegistrarAsistenciaActionPerformed

    private void txtNombreUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreUserKeyReleased
         String texto = txtNombreUser.getText().trim();
        if (!texto.isEmpty()) {
            List<Cliente> resultados = new ArrayList<>();
             try {
                 jComboBoxClientesId.setVisible(true);
                 jLabelCoincidencias.setVisible(true);
                 resultados = clienteController.buscarClientesPorNombre(texto);
             } catch (SQLException ex) {
                 System.getLogger(Asistencias.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
             }

            jComboBoxClientesId.removeAllItems();
            for (Cliente c : resultados) {
                jComboBoxClientesId.addItem(c.getIdCliente() + " - " + c.getNombre());
            }
        } else {
            jComboBoxClientesId.removeAllItems();
        }
    }//GEN-LAST:event_txtNombreUserKeyReleased

    private void txtIdSucursalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdSucursalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdSucursalKeyReleased

    private void jComboBoxClientesIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClientesIdActionPerformed
        if (jComboBoxClientesId.getSelectedItem() != null) {
            String seleccionado = (String) jComboBoxClientesId.getSelectedItem();
            int idCliente = Integer.parseInt(seleccionado.split(" - ")[0]);
            txtIdUser.setText(String.valueOf(idCliente));
        }
    }//GEN-LAST:event_jComboBoxClientesIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarAsistencia;
    private javax.swing.JComboBox<String> jComboBoxClientesId;
    private javax.swing.JLabel jLabelCoincidencias;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelNombreCliente;
    private javax.swing.JLabel jLabelSeparador;
    private javax.swing.JLabel jLabelidCliente;
    private javax.swing.JLabel jLabelidSucursal;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txtIdSucursal;
    private javax.swing.JTextField txtIdUser;
    private javax.swing.JTextField txtNombreUser;
    // End of variables declaration//GEN-END:variables
}
