package com.archivos.fitmanager.ui.recepcion;

import com.archivos.fitmanager.dao.PagoDAO;
import com.archivos.fitmanager.db.DBConfig;
import com.archivos.fitmanager.model.Pago;
import java.sql.Connection;
import java.sql.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author vicente
 */
public class Membresia extends javax.swing.JPanel {

    /**
     * Creates new form Membresia
     */
    public Membresia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelMenu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelTravel2 = new javax.swing.JLabel();
        jComboBoxTipoPago = new javax.swing.JComboBox<>();
        jLabelPago = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jLabelPago1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtFechaFin = new java.awt.TextField();
        btnRegistrarPago = new javax.swing.JButton();
        jLabelIdCliente = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtIdCliente = new javax.swing.JTextField();
        txtFechaInicio = new java.awt.TextField();

        setBackground(new java.awt.Color(33, 45, 62));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelMenu.setBackground(new java.awt.Color(33, 45, 62));
        jpanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("____________");
        jpanelMenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, -1, 30));

        jLabelTravel2.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 24)); // NOI18N
        jLabelTravel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTravel2.setText("PAGO");
        jpanelMenu.add(jLabelTravel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 90, 60));

        add(jpanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 80));

        jComboBoxTipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxTipoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoPagoActionPerformed(evt);
            }
        });
        add(jComboBoxTipoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 310, 40));

        jLabelPago.setFont(new java.awt.Font("Gotham Thin", 0, 24)); // NOI18N
        jLabelPago.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPago.setText("Monto");
        add(jLabelPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 80, 30));

        txtMonto.setBackground(new java.awt.Color(33, 45, 62));
        txtMonto.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtMonto.setForeground(new java.awt.Color(195, 218, 227));
        txtMonto.setBorder(null);
        txtMonto.setCaretColor(new java.awt.Color(73, 181, 172));
        add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 430, 40));

        jLabelPago1.setFont(new java.awt.Font("Gotham Thin", 0, 24)); // NOI18N
        jLabelPago1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPago1.setText("Tipo Pago");
        add(jLabelPago1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 130, 30));

        jSeparator3.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator3.setForeground(new java.awt.Color(73, 181, 172));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 310, 10));

        txtFechaFin.setText("textField1");
        txtFechaFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaFinActionPerformed(evt);
            }
        });
        add(txtFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 320, 30));

        btnRegistrarPago.setBackground(new java.awt.Color(73, 181, 172));
        btnRegistrarPago.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnRegistrarPago.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarPago.setText("REGISTRAR PAGO");
        btnRegistrarPago.setBorderPainted(false);
        btnRegistrarPago.setContentAreaFilled(false);
        btnRegistrarPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarPago.setFocusPainted(false);
        btnRegistrarPago.setFocusable(false);
        btnRegistrarPago.setRequestFocusEnabled(false);
        btnRegistrarPago.setVerifyInputWhenFocusTarget(false);
        btnRegistrarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPagoActionPerformed(evt);
            }
        });
        add(btnRegistrarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, 210, 60));

        jLabelIdCliente.setFont(new java.awt.Font("Gotham Thin", 0, 24)); // NOI18N
        jLabelIdCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIdCliente.setText("Id Cliente");
        add(jLabelIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 100, 30));

        jSeparator4.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator4.setForeground(new java.awt.Color(73, 181, 172));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 310, 10));

        txtIdCliente.setBackground(new java.awt.Color(33, 45, 62));
        txtIdCliente.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txtIdCliente.setForeground(new java.awt.Color(195, 218, 227));
        txtIdCliente.setBorder(null);
        txtIdCliente.setCaretColor(new java.awt.Color(73, 181, 172));
        add(txtIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 430, 40));

        txtFechaInicio.setText("textField1");
        txtFechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaInicioActionPerformed(evt);
            }
        });
        add(txtFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 320, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTipoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoPagoActionPerformed

    private void txtFechaFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaFinActionPerformed

    private void btnRegistrarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPagoActionPerformed
        try (Connection conn = DBConfig.getConnection()) {
        Pago pago = new Pago();
        pago.setMonto(Double.parseDouble(txtMonto.getText().trim()));
        pago.setIdCliente(Integer.parseInt(txtIdCliente.getText().trim()));

        String tipoSeleccionado = jComboBoxTipoPago.getSelectedItem().toString();
        if (tipoSeleccionado.equals("BASICO")) {
            pago.setIdTipoPago(1); // id_tipo_pago BASICO
            pago.setFechaInicio(Date.valueOf(txtFechaInicio.getText().trim()));
            pago.setFechaFin(Date.valueOf(txtFechaFin.getText().trim()));

            PagoDAO dao = new PagoDAO(conn);
            if (dao.registrarPagoBasico(pago)) {
                JOptionPane.showMessageDialog(this, "Pago básico registrado correctamente.");
            }
        } else {
            pago.setIdTipoPago(2); // id_tipo_pago SERVICIO_ADICIONAL

            PagoDAO dao = new PagoDAO(conn);
            int idPago = dao.registrarPagoServicio(pago);
            if (idPago > 0) {
                JOptionPane.showMessageDialog(this, "Pago de servicios registrado. ID: " + idPago);
                // Aquí luego registramos en pago_servicio los servicios adicionales
            }
        }
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al registrar pago: " + ex.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnRegistrarPagoActionPerformed

    private void txtFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaInicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarPago;
    private javax.swing.JComboBox<String> jComboBoxTipoPago;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelIdCliente;
    private javax.swing.JLabel jLabelPago;
    private javax.swing.JLabel jLabelPago1;
    private javax.swing.JLabel jLabelTravel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel jpanelMenu;
    private java.awt.TextField txtFechaFin;
    private java.awt.TextField txtFechaInicio;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
